# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Siddhanth Rao
title: Software Engineer
email: siddhanthrao5858@gmail.com  iit2016113@iiita.ac.in
website: https://idkyamhere.github.io/Siddhanth_Rao/

# Social links
github_username:  IDKYamHere
instagram_username: idkyamhere
linkedin_username: Siddhanth Rao

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: Test ABCD

# Projects Section
 projects_title: Project1
 projects_title: Project1
 projects_title: Project1

# Experience Section
 experience_title: Experience

# Education Section
 educaton_title: Indian Institute of Information Technology, Allahabad.
 educaton_title: Sri Chaitanya Junior Kalasala, Hyderabad.
 educaton_title: Gitanjali Devshala

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
